// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEypYUe8Y783rzu7Kdp4vADV61Zx3EV1Q',
    appId: '1:496963264302:web:30c58db6cda6ae199e24bf',
    messagingSenderId: '496963264302',
    projectId: 'patientdetails-35e27',
    authDomain: 'patientdetails-35e27.firebaseapp.com',
    storageBucket: 'patientdetails-35e27.appspot.com',
    measurementId: 'G-BYT3ZM1DXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTb1zEH77VjABOSa8UnuaPXhfUMbo4r68',
    appId: '1:496963264302:android:b3603bf9fef4b5b49e24bf',
    messagingSenderId: '496963264302',
    projectId: 'patientdetails-35e27',
    storageBucket: 'patientdetails-35e27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXsxSw_nfbo2LDecOehoCkDtt3U7oZdbc',
    appId: '1:496963264302:ios:5951a123abc1d4f49e24bf',
    messagingSenderId: '496963264302',
    projectId: 'patientdetails-35e27',
    storageBucket: 'patientdetails-35e27.appspot.com',
    iosBundleId: 'com.example.phd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXsxSw_nfbo2LDecOehoCkDtt3U7oZdbc',
    appId: '1:496963264302:ios:6d480e18a34f62239e24bf',
    messagingSenderId: '496963264302',
    projectId: 'patientdetails-35e27',
    storageBucket: 'patientdetails-35e27.appspot.com',
    iosBundleId: 'com.example.phd.RunnerTests',
  );
}
